version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./config/users.xml:/etc/clickhouse-server/users.xml
      - ./config/users.d/default-password.xml:/etc/clickhouse-server/users.d/default-password.xml
    ports:
      - "8123:8123"
    entrypoint: /bin/bash -c "cp /etc/clickhouse-server/users.xml /etc/clickhouse-server/config.d/ && exec /entrypoint.sh"

volumes:
  clickhouse_data: